[x,y] = meshgrid(0:0.01:1);
W = max(x+y-1,0);
M = min(x,y);
Z = x.*y;
subplot(3,3,1); mesh(x,y,W);title('W=max(x+y-1,0)');
subplot(3,3,2); mesh(x,y,M);title('M=min(x,y)');
subplot(3,3,3); mesh(x,y,Z);title('Z=x.*y');
subplot(3,3,4); mesh(x,y,W);title('C=[W,M]');
hold on;
subplot(3,3,4); mesh(x,y,M);title('C=[W,M]');
hold off;
subplot(3,3,5); mesh(x,y,Z);title('M & Z');
hold on;
subplot(3,3,5); mesh(x,y,M);title('M & Z');
hold off;
subplot(3,3,6); contour(M); title('M');
hold on;
subplot(3,3,6); contour(Z); title('M');
hold off;
subplot(3,3,7); contour(W); title('W');
subplot(3,3,8); contour(M); title('M');
subplot(3,3,9); contour(Z); title('Z');